version: '3.8'

services:
  app:
    image: node:22
    container_name: nextjs-app
    working_dir: /usr/app
    ports:
      - '3001:3000'
    volumes:
      - ./src:/usr/app
    stdin_open: true
    tty: true
