version: '3.8'

services:
  app:
    image: node:22
    container_name: nextjs-app
    working_dir: /usr/app
    ports:
      - '3001:3000'
    volumes:
      - ./src:/usr/app
    command: sh -c "npm install --legacy-peer-deps && npm run dev"
    environment:
      NODE_ENV: development
